import Head from "next/head"
import { useEffect, useRef, useState } from "react"
import Trex from "@/game-utils/Trex"
import Runner from "@/game-utils/Runner"

export default function Home() {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const spriteRef = useRef<HTMLImageElement>(null)
  const [rect, setRect] = useState([600, 150])

  useEffect(() => {
    if (!canvasRef.current) return
    const canvas = canvasRef.current
    const ctx = canvas.getContext("2d")
    if (!ctx) return
    canvas.width = rect[0]
    canvas.height = rect[1]
    if (!spriteRef.current) return
    const spriteImage = spriteRef.current
    const runner = new Runner(ctx, spriteImage)
    const tRex = Trex.getInstance(ctx, spriteImage)
    tRex.draw(40, 2)

    return () => {
      console.log("---Component Destroyed----")
      runner.stopListening()
    }
  }, [])

  // useEffect(() => {
  //   console.log("2nd useEffect")
  // }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <canvas id="game" ref={canvasRef} width="640" height="400"></canvas>
      <div id="offline-resources">
        <img id="offline-resources-1x" src="/sprite@1x.png" alt="sprite" />
        <img id="offline-resources-2x" src="/sprite@2x.png" alt="sprite" ref={spriteRef} />
      </div>
      <style jsx>
        {`
          #offline-resources {
            display: none;
          }

          img[id*="offline-resources-"] {
            // width: 1233px;
          }
        `}
      </style>
    </>
  )
}
