import Head from "next/head"
import { useEffect } from "react"
import Runner from "@/game/Runner"

const assetPrefix = process.env.NODE_ENV === "production" ? "/chrome-dino" : ""

export default function Home() {
  useEffect(() => {
    const runner = Runner.getInstance("#main-frame-error")

    return () => {
      console.log("---Component Destroyed----")
      runner.stopListening()
    }
  }, [])

  return (
    <>
      <Head>
        <title>Chrome Dino</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="main-frame-error" className="interstitial-wrapper">
        <div className="runner-container">
          <canvas className="runner-canvas"></canvas>
        </div>
      </div>
      <div id="offline-resources">
        <img id="offline-resources-1x" src={`${assetPrefix}/sprite@1x.png`} alt="offline-resources-1x" />
        <img id="offline-resources-2x" src={`${assetPrefix}/sprite@2x.png`} alt="offline-resources-2x" />
      </div>
    </>
  )
}
