import Head from "next/head"
import { useEffect, useRef, useState } from "react"
import Runner from "@/game-utils/Runner"

export default function Home() {
  const runnerContainer = useRef<HTMLDivElement>(null)
  const runnerCanvas = useRef<HTMLCanvasElement>(null)
  const offlineResources = useRef<HTMLImageElement>(null)
  const [rect, setRect] = useState([600, 150])

  useEffect(() => {
    if (!runnerContainer.current) return
    if (!runnerCanvas.current) return
    if (!offlineResources.current) return

    const canvas = runnerCanvas.current
    const ctx = canvas.getContext("2d")
    if (!ctx) return
    canvas.width = rect[0]
    canvas.height = rect[1]
    const runner = new Runner(ctx, offlineResources.current, runnerContainer.current)

    return () => {
      console.log("---Component Destroyed----")
      runner.stopListening()
    }
  }, [])

  return (
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="interstitial-wrapper">
        <div className="runner-container" ref={runnerContainer}>
          <canvas className="runner-canvas" ref={runnerCanvas} width="640" height="400"></canvas>
        </div>
      </div>
      <div id="offline-resources">
        <img id="offline-resources-1x" src="/sprite@1x.png" alt="sprite" />
        <img id="offline-resources-2x" src="/sprite@2x.png" alt="sprite" ref={offlineResources} />
      </div>
    </main>
  )
}
